name: CI

on: [push]

jobs:
  build:


    runs-on: ubuntu-latest


    steps:
    - uses: action/checkout@v1
    - name: Run a one-line script
      run: echo Helo, worls!
    - name: Run a multi-line script
      run: |
        echo Add other action to build,
        echo test, and deploy your projec.
